name: Build and Push to GCR

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: us-central1-c

jobs:
  setup-build-publish-webhook:
    name: Setup, Build, Publish, Webhook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Build
        run: |-
          npm i
          npm run build
          mkdir -p /tmp/dist
          mv /home/runner/work/coreum-docs/coreum-docs/src/.vuepress/dist /tmp/dist

      - uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '/tmp/dist/dist'
          destination: ${{ secrets.BUCKET_NAME }}
          parent: false